import { 
  Search, 
  FileText, 
  Image, 
  FileImage, 
  Code, 
  Globe, 
  PenTool, 
  Brain, 
  Calculator,
  Zap,
  Eye,
  Shield,
  Link,
  BarChart3,
  Palette,
  Scissors,
  Download,
  Upload,
  Maximize,
  Minimize,
  RotateCw,
  Crop,
  Filter,
  Hash,
  Type,
  AlignLeft,
  Clock,
  Counter,
  FileCode,
  Database,
  Settings,
  Wrench,
  Target,
  TrendingUp,
  Award,
  CheckCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Star,
  Heart,
  Share,
  Copy,
  Paste,
  Save,
  Folder,
  FolderOpen,
  Archive,
  Unarchive,
  Lock,
  Unlock,
  Key,
  Shuffle,
  RefreshCw,
  ArrowUpDown,
  ArrowLeftRight,
  Merge,
  Split,
  Layers,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  Plus,
  Minus,
  Multiply,
  Divide,
  Percent,
  Equal,
  MoreHorizontal,
  MoreVertical,
  Menu,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock3,
  Timer,
  Stopwatch,
  Play,
  Pause,
  Square,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Video,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Desktop,
  Server,
  Cloud,
  Wifi,
  Bluetooth,
  Usb,
  HardDrive,
  Cpu,
  MemoryStick,
  Power,
  Battery,
  BatteryLow,
  Plug,
  Zap as Lightning,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Thermometer,
  Wind,
  Compass,
  Navigation,
  Map,
  Route,
  Car,
  Truck,
  Plane,
  Ship,
  Train,
  Bike,
  Walk,
  Run,
  Home,
  Building,
  Store,
  Factory,
  School,
  Hospital,
  Bank,
  Hotel,
  Restaurant,
  Coffee,
  ShoppingCart,
  ShoppingBag,
  Gift,
  CreditCard,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Bitcoin,
  TrendingDown,
  PieChart,
  LineChart,
  AreaChart,
  Activity,
  Pulse,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Film,
  Clapperboard,
  Music,
  Disc,
  Album,
  PlayCircle,
  PauseCircle,
  StopCircle,
  FastForward,
  Rewind,
  Repeat,
  Repeat1,
  Shuffle as ShuffleIcon,
  BookOpen,
  Book,
  Bookmark,
  Library,
  GraduationCap,
  School as Academy,
  Users,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Crown,
  Medal,
  Trophy,
  Flag,
  Bookmark as Flag2,
  Tag,
  Tags,
  Paperclip,
  Pin,
  Pushpin,
  Thumbtack,
  Magnet,
  Anchor,
  Feather,
  Pen,
  Pencil,
  Edit,
  Edit2,
  Edit3,
  Eraser,
  Highlighter,
  Paintbrush,
  Paintbrush2,
  Pipette,
  Dropper,
  Brush,
  Spray,
  Roller,
  PaintBucket,
  Swatch,
  Rainbow,
  Contrast,
  Brightness,
  Saturation,
  Hue,
  Blur,
  Focus,
  Lens,
  Aperture,
  Shutter,
  Iso,
  Flash,
  FlashOff,
  Flashlight,
  Bulb,
  Lamp,
  Candle,
  Flame,
  Fire,
  Snowflake,
  Droplet,
  Droplets,
  Waves,
  Umbrella,
  UmbrellaOff,
  Cloudy,
  PartlyCloudy,
  CloudyRain,
  Tornado,
  Hurricane,
  Earthquake,
  Volcano,
  Mountain,
  Hill,
  Valley,
  Desert,
  Forest,
  Tree,
  TreeDeciduous,
  TreeEvergreen,
  Flower,
  Flower2,
  Leaf,
  Leaves,
  Grass,
  Cactus,
  Mushroom,
  Apple,
  Banana,
  Cherry,
  Grape,
  Orange,
  Peach,
  Pear,
  Strawberry,
  Watermelon,
  Carrot,
  Corn,
  Potato,
  Tomato,
  Pepper,
  Onion,
  Garlic,
  Lettuce,
  Broccoli,
  Cabbage,
  Cauliflower,
  Cucumber,
  Eggplant,
  Pumpkin,
  Radish,
  Spinach,
  Turnip,
  Beet,
  Avocado,
  Coconut,
  Kiwi,
  Lemon,
  Lime,
  Mango,
  Papaya,
  Pineapple,
  Plum,
  Pomegranate,
  Artichoke,
  Asparagus,
  Brussels,
  Celery,
  Chard,
  Fennel,
  Kale,
  Leek,
  Okra,
  Parsnip,
  Rutabaga,
  Shallot,
  SquashWinter,
  Zucchini
} from "lucide-react";

// Tool icon mapping based on tool name patterns and functionality
export const TOOL_ICON_MAP: Record<string, any> = {
  // SEO Tools
  "seo-score-checker": Search,
  "page-speed-test": Zap,
  "keyword-density-checker": Hash,
  "meta-tag-analyzer": Code,
  "robots-txt-generator": Settings,
  "sitemap-generator": Globe,
  "backlink-checker": Link,
  "domain-authority-checker": Shield,
  "google-serp-checker": TrendingUp,
  "social-media-preview": Share,
  "structured-data-tester": Database,
  "website-analyzer": BarChart3,
  "competitor-analysis": Target,
  "local-seo-checker": MapPin,
  "mobile-friendly-test": Smartphone,
  "ssl-checker": Lock,
  "whois-lookup": Info,
  "dns-lookup": Server,
  "redirect-checker": ArrowLeftRight,
  "broken-link-checker": AlertCircle,
  "canonical-url-checker": Link,
  "hreflang-checker": Globe,
  "schema-markup-generator": Code,
  "open-graph-generator": Share,
  "twitter-card-generator": Share,
  "favicon-generator": Image,
  "url-structure-analyzer": Folder,
  "content-gap-analysis": Eye,
  "rank-tracker": TrendingUp,
  "serp-simulator": Monitor,
  "keyword-planner": Target,
  "search-volume-checker": BarChart3,

  // Text Tools
  "word-counter": Counter,
  "character-counter": Type,
  "text-case-converter": Type,
  "text-reverser": RefreshCw,
  "duplicate-line-remover": Scissors,
  "text-to-slug": Link,
  "lorem-ipsum-generator": FileText,
  "text-diff-checker": ArrowUpDown,
  "text-encoder-decoder": Code,
  "password-generator": Key,
  "hash-generator": Hash,
  "qr-code-generator": Grid,
  "barcode-generator": List,
  "text-to-speech": Volume2,
  "speech-to-text": Mic,
  "language-detector": Globe,
  "text-translator": Globe,
  "readability-checker": BookOpen,
  "plagiarism-checker": Eye,
  "grammar-checker": CheckCircle,
  "spell-checker": PenTool,
  "text-summarizer": Minimize,
  "text-extractor": Download,
  "regex-tester": Code,
  "markdown-to-html": Code,
  "html-to-markdown": Code,
  "json-formatter": Code,
  "xml-formatter": Code,
  "csv-to-json": ArrowLeftRight,
  "json-to-csv": ArrowLeftRight,
  "url-encoder": Code,

  // PDF Tools
  "pdf-merger": Merge,
  "pdf-splitter": Split,
  "pdf-compressor": Minimize,
  "pdf-to-word": FileText,
  "word-to-pdf": FileText,
  "pdf-to-excel": Table,
  "excel-to-pdf": Table,
  "pdf-to-powerpoint": FileImage,
  "powerpoint-to-pdf": FileImage,
  "pdf-to-image": Image,
  "image-to-pdf": Image,
  "pdf-password-remover": Unlock,
  "pdf-password-protector": Lock,
  "pdf-page-rotator": RotateCw,
  "pdf-page-extractor": Download,
  "pdf-watermark-adder": Layers,
  "pdf-watermark-remover": Eraser,
  "pdf-text-extractor": FileText,
  "pdf-form-filler": Edit,
  "pdf-optimizer": Settings,
  "pdf-reader": BookOpen,
  "pdf-editor": Edit,
  "pdf-annotator": PenTool,
  "pdf-signature": Pen,
  "pdf-bookmarks": Bookmark,
  "pdf-metadata-editor": Settings,
  "pdf-page-numberer": Hash,
  "pdf-table-extractor": Table,
  "pdf-ocr": Eye,
  "pdf-validator": CheckCircle,
  "pdf-repair": Wrench,
  "pdf-thumbnail-generator": Image,

  // Image Tools
  "image-compressor": Minimize,
  "image-resizer": Maximize,
  "image-cropper": Crop,
  "image-rotator": RotateCw,
  "image-format-converter": ArrowLeftRight,
  "background-remover": Layers,
  "image-upscaler": TrendingUp,
  "photo-editor": Edit,
  "image-filter": Filter,
  "color-picker": Pipette,
  "image-to-text": FileText,
  "watermark-adder": Layers,
  "watermark-remover": Eraser,
  "image-optimizer": Settings,
  "thumbnail-generator": Image,
  "favicon-creator": Image,
  "logo-maker": Palette,
  "meme-generator": Image,
  "collage-maker": Grid,
  "image-merger": Merge,
  "image-splitter": Split,
  "noise-remover": Filter,
  "blur-effect": Blur,
  "sharpen-effect": Focus,
  "brightness-adjuster": Sun,
  "contrast-adjuster": Contrast,
  "saturation-adjuster": Palette,
  "hue-adjuster": Rainbow,
  "grayscale-converter": Filter,
  "sepia-effect": Filter,
  "vintage-effect": Camera,
  "cartoon-effect": Brush,

  // Converter Tools
  "unit-converter": ArrowLeftRight,
  "currency-converter": DollarSign,
  "temperature-converter": Thermometer,
  "length-converter": ArrowLeftRight,
  "weight-converter": ArrowUpDown,
  "area-converter": Grid,
  "volume-converter": Droplet,
  "speed-converter": Zap,
  "time-converter": Clock,
  "angle-converter": Compass,
  "pressure-converter": Gauge,
  "energy-converter": Lightning,
  "power-converter": Plug,
  "frequency-converter": Radio,
  "data-converter": Database,
  "file-converter": ArrowLeftRight,
  "audio-converter": Headphones,
  "video-converter": Video,
  "document-converter": FileText,
  "spreadsheet-converter": Table,
  "presentation-converter": FileImage,
  "ebook-converter": BookOpen,
  "archive-converter": Archive,
  "font-converter": Type,
  "color-converter": Palette,
  "coordinate-converter": MapPin,
  "timezone-converter": Globe,
  "date-converter": Calendar,
  "number-base-converter": Calculator,
  "encoding-converter": Code,
  "compression-converter": Minimize,
  "vector-converter": Edit,

  // Code Tools
  "code-formatter": Code,
  "code-minifier": Minimize,
  "code-beautifier": Palette,
  "syntax-highlighter": Paintbrush,
  "code-validator": CheckCircle,
  "html-validator": Code,
  "css-validator": Palette,
  "javascript-validator": Code,
  "json-validator": Database,
  "xml-validator": Code,
  "sql-formatter": Database,
  "regex-builder": Code,
  "color-palette-generator": Palette,
  "gradient-generator": Rainbow,
  "css-generator": Palette,
  "html-generator": Code,
  "meta-tag-generator": Code,
  "robots-txt-validator": Settings,
  "htaccess-generator": Settings,
  "api-tester": Zap,
  "webhook-tester": Link,
  "cors-tester": Shield,
  "http-status-checker": Info,
  "port-scanner": Search,
  "ping-test": Activity,
  "traceroute": Route,
  "network-scanner": Wifi,
  "ip-geolocation": MapPin,
  "user-agent-parser": Info,
  "base64-encoder": Code,
  "url-shortener": Link,

  // Website Tools
  "website-screenshot": Camera,
  "website-downloader": Download,
  "website-monitor": Monitor,
  "uptime-checker": Activity,
  "performance-test": TrendingUp,
  "security-scan": Shield,
  "malware-scanner": Shield,
  "vulnerability-scanner": AlertCircle,
  "ssl-certificate-checker": Lock,
  "domain-expiry-checker": Calendar,
  "hosting-checker": Server,
  "cdn-checker": Cloud,
  "email-validator": Mail,
  "spam-checker": Shield,
  "blacklist-checker": AlertCircle,
  "reputation-checker": Star,
  "social-share-counter": Share,
  "analytics-checker": BarChart3,
  "cookie-scanner": Settings,
  "privacy-policy-generator": FileText,
  "terms-generator": FileText,
  "gdpr-checker": Shield,
  "accessibility-checker": Eye,
  "w3c-validator": CheckCircle,
  "microdata-checker": Database,
  "amp-validator": Zap,
  "pagespeed-insights": TrendingUp,
  "lighthouse-checker": Search,
  "core-web-vitals": Activity,
  "browser-compatibility": Monitor,
  "responsive-design-checker": Smartphone,
  "mobile-usability": Smartphone,

  // Writing & Grammar Tools
  "grammar-fixer": CheckCircle,
  "spell-corrector": PenTool,
  "punctuation-checker": Type,
  "style-checker": Edit,
  "tone-analyzer": Heart,
  "readability-scorer": BookOpen,
  "writing-assistant": PenTool,
  "content-optimizer": TrendingUp,
  "headline-analyzer": Type,
  "meta-description-optimizer": FileText,
  "article-spinner": RefreshCw,
  "content-rewriter": Edit,
  "paraphrasing-tool": RefreshCw,
  "sentence-rephraser": ArrowLeftRight,
  "synonym-finder": BookOpen,
  "antonym-finder": ArrowUpDown,
  "rhyme-finder": Music,
  "alliteration-generator": Type,
  "acronym-generator": Hash,
  "name-generator": User,
  "title-generator": Type,
  "slogan-generator": Award,
  "blog-idea-generator": Brain,
  "essay-topic-generator": BookOpen,
  "research-assistant": Search,
  "citation-generator": Quote,
  "bibliography-maker": Library,
  "plagiarism-detector": Eye,
  "content-analyzer": BarChart3,
  "keyword-extractor": Target,
  "topic-extractor": Tag,
  "sentiment-analyzer": Heart,

  // AI Tools
  "ai-writer": Brain,
  "ai-chatbot": Brain,
  "ai-translator": Globe,
  "ai-summarizer": Minimize,
  "ai-analyzer": BarChart3,
  "ai-generator": Zap,
  "ai-optimizer": TrendingUp,
  "machine-learning": Brain,
  "neural-network": Brain,
  "deep-learning": Brain,
  "natural-language": Type,
  "text-classification": Tag,
  "sentiment-analysis": Heart,
  "entity-recognition": Target,
  "topic-modeling": Grid,
  "language-detection": Globe,
  "speech-recognition": Mic,
  "image-recognition": Eye,
  "object-detection": Target,
  "face-recognition": User,
  "ocr-scanner": Eye,
  "document-parser": FileText,
  "data-extraction": Download,
  "pattern-recognition": Search,
  "anomaly-detection": AlertCircle,
  "predictive-analytics": TrendingUp,
  "recommendation-engine": Star,
  "personalization": User,
  "automation": Settings,
  "workflow-optimizer": TrendingUp,
  "decision-support": CheckCircle,
  "smart-assistant": Brain,

  // Math & Calculation Tools
  "calculator": Calculator,
  "scientific-calculator": Calculator,
  "graphing-calculator": LineChart,
  "matrix-calculator": Grid,
  "equation-solver": Equal,
  "derivative-calculator": TrendingUp,
  "integral-calculator": AreaChart,
  "limit-calculator": Target,
  "statistics-calculator": BarChart3,
  "probability-calculator": Percent,
  "combination-calculator": Shuffle,
  "permutation-calculator": ArrowLeftRight,
  "fraction-calculator": Divide,
  "percentage-calculator": Percent,
  "ratio-calculator": ArrowLeftRight,
  "proportion-calculator": Equal,
  "area-calculator": Grid,
  "volume-calculator": Droplet,
  "perimeter-calculator": Square,
  "circumference-calculator": Circle,
  "triangle-calculator": Triangle,
  "circle-calculator": Circle,
  "rectangle-calculator": Square,
  "square-calculator": Square,
  "polygon-calculator": Grid,
  "coordinate-calculator": MapPin,
  "distance-calculator": Route,
  "midpoint-calculator": Target,
  "slope-calculator": TrendingUp,
  "angle-calculator": Compass,
  "trigonometry-calculator": Triangle,
  "logarithm-calculator": TrendingUp,
  "exponential-calculator": TrendingUp,
};

// Function to get icon for a tool
export function getToolIcon(toolSlug: string) {
  const icon = TOOL_ICON_MAP[toolSlug];
  return icon || Wrench; // Default icon if not found
}

// Function to get all available icons for the icon picker
export function getAllIcons() {
  return {
    // Basic
    Search, FileText, Image, Code, Globe, PenTool, Brain, Calculator,
    
    // Actions
    Zap, Eye, Shield, Link, Settings, Wrench, Target, TrendingUp,
    
    // Media
    Camera, Video, Music, Volume2, Mic, Headphones,
    
    // Files
    Download, Upload, Archive, Folder, Save, Copy,
    
    // Editing
    Edit, Scissors, Crop, RotateCw, Filter, Palette,
    
    // Math
    Plus, Minus, Multiply, Divide, Percent, Equal,
    
    // Communication
    Mail, Phone, Share, Users, User,
    
    // Time
    Calendar, Clock, Timer, Stopwatch,
    
    // Status
    CheckCircle, AlertCircle, Info, Star, Award,
    
    // Navigation
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Home,
    
    // Tech
    Database, Server, Cloud, Wifi, Monitor, Smartphone,
    
    // Business
    TrendingUp, BarChart3, PieChart, DollarSign, CreditCard,
    
    // Design
    Paintbrush, Brush, Layers, Grid, Type, Rainbow,
  };
}

// Categories for icon picker
export const ICON_CATEGORIES = {
  basic: ['Search', 'FileText', 'Image', 'Code', 'Globe', 'PenTool', 'Brain', 'Calculator'],
  actions: ['Zap', 'Eye', 'Shield', 'Link', 'Settings', 'Wrench', 'Target', 'TrendingUp'],
  media: ['Camera', 'Video', 'Music', 'Volume2', 'Mic', 'Headphones'],
  files: ['Download', 'Upload', 'Archive', 'Folder', 'Save', 'Copy'],
  editing: ['Edit', 'Scissors', 'Crop', 'RotateCw', 'Filter', 'Palette'],
  math: ['Plus', 'Minus', 'Multiply', 'Divide', 'Percent', 'Equal'],
  communication: ['Mail', 'Phone', 'Share', 'Users', 'User'],
  time: ['Calendar', 'Clock', 'Timer', 'Stopwatch'],
  status: ['CheckCircle', 'AlertCircle', 'Info', 'Star', 'Award'],
  navigation: ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Home'],
  tech: ['Database', 'Server', 'Cloud', 'Wifi', 'Monitor', 'Smartphone'],
  business: ['TrendingUp', 'BarChart3', 'PieChart', 'DollarSign', 'CreditCard'],
  design: ['Paintbrush', 'Brush', 'Layers', 'Grid', 'Type', 'Rainbow'],
};

// Function to get icon name from component
export function getIconName(IconComponent: any): string {
  return IconComponent.displayName || IconComponent.name || 'Unknown';
}

// Function to get icon component from name
export function getIconFromName(iconName: string) {
  const allIcons = getAllIcons();
  return (allIcons as any)[iconName] || Wrench;
}